name: mmCMS Installer CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, json
          coverage: none

      - uses: "ramsey/composer-install@v1"

      - name: Run linting
        run: composer run-script check-style

      - name: Run static analysis
        run: composer run-script stan

      - name: Execute tests
        run: composer run-script test -- --stop-on-failure
